---
title: "icpsr-import"
author: "Brooks Ambrose"
date: "September 8, 2016"
output: html_document
---

```{r init, include=FALSE}
rm(list=ls())
cat('\014')
knitr::opts_chunk$set(echo =T,eval=F)
source('icpsr-import.R')
require(data.table)
```

```{r scrape2ftxt}
files<-scraped2RData('/Volumes/Iomega_HDD/Scraped Hearings/')
```

```{r icpsr2ftxt}
icpsr2RData.f(src.dir = '/Users/bambrose/Dropbox/2016-2017/2016-2017_A-Fall/CTAWG/ICPSR_33501')
```

```{r icpsr2bow}
icpsr2bow<-icpsr2bow.f(src.dir = '/Volumes/Iomega_HDD 1/Scraped Hearings')
save(icpsr2bow,file='icpsr2bow.RData')
```

```{r html2dict}
# Scrape a security dictionary
# load packages
library(RCurl)
library(XML)

# download html
dict <- getURL("https://myvocabulary.com//wordlist/alphalary_popup.php?wordlist_id=197", followlocation = TRUE)

# parse html
dict <- htmlParse(dict, asText=TRUE)
dict <- xpathSApply(dict, "//span", xmlValue)

#preprocess
dict<-txt2pp.f(dict)
save(dict,file='security-dict.RData')
```

```{r bow2samp}
# load saved 1-gram database
#load('icpsr1grambow.RData')
load('icpsr2bow.RData')
# code year from speechID
icpsr2bow$speech[,y:=factor(substr(speechID,4,7))]

#define sample

# keep terms appearing in more than 100 docs
setkey(icpsr2bow$speech,t)
v<-icpsr2bow$speech[,.N,by=t]
setkey(v,N)
docs<-icpsr2bow$speech[list(v[!list(1:100),t])]

# keep docs longer than 100 words
setkey(icpsr2bow$descr,word.count)
id<-icpsr2bow$descr[list(1:100),unique(speechID)]
setkey(docs,speechID)
docs<-docs[!list(as.character(id))]

# summarize which are in sample
docs[,indict:=t%in%dict]
sd<-docs[,list(ps=mean(indict)),by=speechID]
sd[,samp:=cut(ps,breaks=-1:1,labels=c('0','>0'),include.lowest = T)]

# keep only in sample
setkey(docs,t)
id<-docs[list(dict),unique(as.character(speechID))]
setkey(docs,speechID)
docs<-docs[id]


# save security sample
sdb<-list(sum=sd,dict=dict,docs=docs)
save(sdb,file='security-sample.RData')
rm(sdb)

cat('Sample is '
		,round(length(docs[,unique(speechID)])/length(icpsr2bow$speech[,unique(speechID)])*100,2)
		,'% of original documents and '
		,round(length(docs[,unique(t)])/length(icpsr2bow$speech[,unique(t)])*100,2)
		,'% of pre-processed tokens.'
		,sep='')

```


```{r bow2ts}
# build time series showing frequency of security docs in unaltered sample
ts<-merge(icpsr2bow$speech[dict,list(dict=sum(N)),by=y],icpsr2bow$speech[,list(base=sum(N)),by=y],by='y')
ts[,y:=as.integer(as.character(y))]


#plot
png('security104-110.png',h=480,w=640)
par(mar = c(3,5,3,5))
with(ts, plot(y, dict/base, type="l", col="red3",xlab=NA,ylab='Proportion of All Terms',main='Security Terms in Floor Speeches of 104th-110th U.S. Congresses'))
abline(v=c(1995,1999,2001),col='gray',lwd=3)
par(new = T)
with(ts, plot(y, dict, type='l',lty=2,col='black', axes=F, xlab=NA, ylab=NA))
axis(side = 4)
mtext(side = 4, line = 3, 'Count')
legend("topleft",
			 legend=c('Prop.', "Count"),
			 lty=c(1,2), col=c("red3", "black"))
mtext(c('Oklahoma City','Columbine','9/11'),at=c(1995,1999,2001),side=1,cex=.75,col='darkgray')
dev.off()
```

```{r bow2stm}
load('security-sample.RData')
dict<-sdb$dict # security dictionary
sdb<-sdb$docs 
system.time(bow2stm<-bow2stm.f(sdb))
rm(sdb)
save(bow2stm,file='bow2stm-security.RData')
```

```{r bow2meta}
# "meta" covariates
load('bow2stm-security.RData')
load('icpsr2bow.RData')
setkey(icpsr2bow$descr,speechID)
icpsr2bow$descr<-icpsr2bow$descr[names(bow2stm$documents)]
setkey(icpsr2bow$descr,speakerID)
setkey(icpsr2bow$speaker,id)
meta<-merge(
	x=icpsr2bow$descr
	,y=icpsr2bow$speaker
	,by.x='speakerID',by.y='id'
)
setkey(meta,speechID)
save(meta,file='meta-security.RData')
if(T) {
	require(data.table)
	load("/Volumes/Iomega_HDD 1/CTAWG/speechID.date.num_order_within_file.speakerID.file.line_start.line_end.page.char_count.word_count.RData") # temporary fix for bad dates
	load('meta-security.RData')
	setkey(dt,speechID)
	dim(dt)
	dt<-dt[meta$speechID]
	dim(dt)
	setkey(meta,speechID)
	meta[,date:=NULL]
	tss<-strptime(dt$date,tz='EST',format='%y%m%d')
	days<-as.numeric(tss-min(tss))/60/60/24
	years<-days/356
	ts11<-as.numeric(tss-strptime('010911',tz='EST',format='%y%m%d'))/60/60/24/356

	if(identical(meta$speechID,dt$speechID)) meta[,`:=`(
		date=dt$date
		,days=days
		,years=1995+years
		,sep11=ts11
		)]
	save(meta,file='meta-security-time.RData')
	hist(meta$sep11)

}

```

